version: "3.8"

services:
  web:
    container_name: nginx
    build: nginx
    volumes:
      - ./media:/usr/share/nginx/html/static/images
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    logging:
      driver: "local"

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST: ${SERVER_HOST}
        LOG_LEVEL: ${SERVER_LOG_LEVEL}

    env_file:
      - ./.env
    volumes:
      - ./media:/code/media
    ports:
      - 8000:8000
    depends_on:
      - migrations
    logging:
      driver: "local"



  migrations:
    container_name: migrations
    build: .
    command: bash -c "cd src && alembic upgrade head"
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: "local"

  database:
      container_name: database
      image: postgres:15.4-alpine
      ports:
        - "5432:5432"

      env_file:
        - ./.env
      command:
        - "postgres"
        - "-c"
        - "log_destination=stderr"
        - "-c"
        - "logging_collector=on"
        - "-c"
        - "log_directory=/var/lib/postgresql/data/pg_log"
        - "-c"
        - "work_mem=1024MB"
        - "-c"
        - "maintenance_work_mem=1024MB"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", -U $POSTGRES_DB_NAME ]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
      restart: always



volumes:
  postgres-data:

